# ----------------------------
# agondev Makefile
# util library
# ----------------------------

NAME = util
DESCRIPTION = ""

# ----------------------------
include $(shell agondev-config --makefile)
